### ISSUE TITLE
StrictMode policy violation: android.os.strictmode.WebViewMethodCalledOnWrongThreadViolation

### ISSUE THREAD

**Issue by shukerullah** [tinypass/piano-sdk-for-android#14]
I am getting `StrictMode policy violation: android.os.strictmode.WebViewMethodCalledOnWrongThreadViolation` while calling `ShowTemplateController.reloadWithToken` after `signin`

__Error:__
```
StrictMode policy violation: android.os.strictmode.WebViewMethodCalledOnWrongThreadViolation
        at android.webkit.WebView.checkThread(WebView.java:2592)
        at android.webkit.WebView.evaluateJavascript(WebView.java:882)
        at io.piano.android.composer.showtemplate.ShowTemplateController$Companion.executeJavascriptCode$composer_show_template_release(ShowTemplateController.kt:40)
        at io.piano.android.composer.showtemplate.ShowTemplateController.reloadWithToken(ShowTemplateController.kt:30)
```

__Code:__
```

public void init(String endpoint, String aid, Callback callback) {
    PianoIdClient pianoIdClient = PianoId.init(endpoint, aid)
        .with(new PianoIdCallback<PianoIdToken>()
        {
            @Override
            public void onSuccess(PianoIdToken pianoIdToken)
            {
                onAccessToken(pianoIdToken, callback);
            }
            @Override
            public void onFailure(PianoIdException exception)
            {
                invokeError(exception.getMessage(), callback);
            }
        })
}


private void onAccessToken(PianoIdToken pianoIdToken, Callback callback) {
    if(pianoIdToken != null && pianoIdToken.accessToken != null) {
        if (showTemplateController != null) {
            showTemplateController.reloadWithToken(pianoIdToken.accessToken);
        }
    }
    invokeResponse(callback);
}

**Comment by DeKaN** [comment]
You must call all `composer-show-template` from the UI thread. By the way, in your code check `pianoIdToken != null` is always true

**Comment by DeKaN** [comment]
Closing issue due to inactivity. Please feel free to open it again or create a new one and reference this if you have further questions.
