### ISSUE TITLE
When I was trying to run the `sample` module, then getting exception

### ISSUE THREAD

**Issue by njboro** [tinypass/piano-sdk-for-android#21]
Exception log. Kindly help me to overcome this issue.

Process: io.piano.sample, PID: 10942
    java.lang.RuntimeException: Unable to create application io.piano.sample.PianoSampleApplication: java.lang.IllegalArgumentException: Cannot serialize Kotlin type io.piano.android.id.models.PianoIdToken. Reflective serialization of Kotlin classes without using kotlin-reflect has undefined and unexpected behavior. Please use KotlinJsonAdapterFactory from the moshi-kotlin artifact or use code gen from the moshi-kotlin-codegen artifact.
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6717)
        at android.app.ActivityThread.access$1300(ActivityThread.java:237)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.IllegalArgumentException: Cannot serialize Kotlin type io.piano.android.id.models.PianoIdToken. Reflective serialization of Kotlin classes without using kotlin-reflect has undefined and unexpected behavior. Please use KotlinJsonAdapterFactory from the moshi-kotlin artifact or use code gen from the moshi-kotlin-codegen artifact.
        at com.squareup.moshi.ClassJsonAdapter$1.create(ClassJsonAdapter.java:97)
        at com.squareup.moshi.Moshi.adapter(Moshi.java:145)
        at com.squareup.moshi.Moshi.adapter(Moshi.java:105)
        at com.squareup.moshi.Moshi.adapter(Moshi.java:79)
        at io.piano.sample.PrefsStorage.<init>(PrefsStorage.java:25)
        at io.piano.sample.SimpleDependenciesProvider.<init>(SimpleDependenciesProvider.java:19)
        at io.piano.sample.SimpleDependenciesProvider.getInstance(SimpleDependenciesProvider.java:39)
        at io.piano.sample.PianoSampleApplication.onCreate(PianoSampleApplication.java:38)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6712)
        at android.app.ActivityThread.access$1300(ActivityThread.java:237) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by DeKaN** [comment]
@njboro I've added a simple fix. I'll fix incorrect annotations for accessing `PianoIdTokenJsonAdapter.FACTORY` from Java

**Comment by njboro** [comment]
Thanks @DeKaN . It's working now.
