### ISSUE TITLE
We are getting exception after updating to v2.6.2

### ISSUE THREAD

**Issue by njboro** [tinypass/piano-sdk-for-android#35]
Hi Folks,

I am using Piano v2.6.2, and using Java.

For some devices, we are getting an exception due to below line of code:
gson.fromJson(MyPreference.getInstance(MyApp.getAppContext()).getUserToken(), PianoIdToken.class);

Stacktrace:
Exception: com.google.gson.JsonSyntaxException
Oct 31, 2021 14:58:04
Non-fatal Exception: com.google.gson.JsonSyntaxException: Oct 31, 2021 14:58:04
       at com.google.gson.internal.bind.DateTypeAdapter.deserializeToDate(DateTypeAdapter.java:87)
       at com.google.gson.internal.bind.DateTypeAdapter.read(DateTypeAdapter.java:75)
       at com.google.gson.internal.bind.DateTypeAdapter.read(DateTypeAdapter.java:46)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
       at com.google.gson.Gson.fromJson(Gson.java:932)
       at com.google.gson.Gson.fromJson(Gson.java:897)
       at com.google.gson.Gson.fromJson(Gson.java:846)
       at com.google.gson.Gson.fromJson(Gson.java:817)

Please help us to rectify this.

**Comment by DeKaN** [comment]
Closing issue due to inactivity. Please feel free to open it again or create a new one and reference this if you have further questions.
